Repository modelica/fmi-ls-bus, pull requests merged in 2023-11, with the labels that each got.

#86 79 fix fmi ls bus bugs within headers
  docs/headers/fmi3LsBus.h
  docs/headers/fmi3LsBusCan.h
Labels: bug

#89 Moved header and schema files
  headers/fmi3LsBus.h
  headers/fmi3LsBusCan.h
  schema/fmi3LayeredStandardBusManifest.xsd
Labels: common

#82 Fixed issue 81
  docs/3____physical_signal_abstraction.adoc
  docs/4____network_abstraction.adoc
  docs/examples/X_network4FMI_terminalsAndIcons_highCut.xml
  docs/examples/X_network4FMI_terminalsAndIcons_lowCut.xml
Labels: bug, common

#80 Rename WaitForBusNotification parameter
  docs/4_4_1_can.adoc
Labels: can

#96 Adding some LIN content
  docs/4_4_2_lin.adoc
  docs/images/lin_wake_up.drawio
  docs/images/lin_wake_up.svg
Labels: lin

#101 Fixed issue 100
  docs/4_4_1_can.adoc
Labels: bug, can

#94 Fixed issue #85
  docs/3____physical_signal_abstraction.adoc
Labels: bug, high-cut

#95 Fixed issue #93
  headers/fmi3LsBus.h
  headers/fmi3LsBusCan.h
Labels: bug

#78 Rework of chapter 5.3 to allow triggered Tx_Clock variables
  docs/4____network_abstraction.adoc
  docs/images/low_cut_communication_points.drawio
  docs/images/low_cut_communication_points.svg
  docs/images/low_cut_communication_with_triggered_tx_clock.drawio
  docs/images/low_cut_communication_with_triggered_tx_clock.svg
  docs/images/low_cut_time_based_port_connection.drawio
  docs/images/low_cut_time_based_port_connection.svg
Labels: common

#106 Refactoring fmi-ls-bus headers
  headers/fmi3LsBus.h
  headers/fmi3LsBusCan.h
Labels: bug

#103 Fixing issue #75
  README.md
  docs/4____network_abstraction.adoc
Labels: common, can

#104 >Integration of some formal fixes
  docs/2____common_concepts.adoc
  docs/3____physical_signal_abstraction.adoc
  docs/4_4_1_can.adoc
  docs/4_4_2_lin.adoc
  docs/4____network_abstraction.adoc
Labels: bug
